### ISSUE TITLE
Set up CI, code coverage, etc.

### ISSUE THREAD

**Issue by mwhittaker** [ucbrise/fluent#10]
@cw75, if you could set up all this stuff, that would be great. The project is still young, so it's not incredibly urgent, but I suppose the sooner the better.

**Comment by mwhittaker** [comment]
@cw75 Since we're having so many build problems, we should probably try to set up some CI to help catch some of these things earlier. Do you think you can set this up?

**Comment by cw75** [comment]
Yeah.

**Comment by mwhittaker** [comment]
Sweet.

**Comment by mwhittaker** [comment]
@cw75, any status on this?
