### ISSUE TITLE
Failure to compile on master

### ISSUE THREAD

**Issue by gaberger** [ucbrise/fluent#113]
ubuntu@aria:/vagrant_data/fluent$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

ubuntu@aria:/vagrant_data/fluent$ ./scripts/build.sh Debug 4
-- Boost version: 1.58.0
-- [include directories]
--   /vagrant_data/fluent/build/Debug/src/aws_project/aws-cpp-sdk-core/include
--   /vagrant_data/fluent/build/Debug/src/aws_project/aws-cpp-sdk-s3/include
--   /usr/include
--   /vagrant_data/fluent/build/Debug/src/cassandra_project/include
--   /vagrant_data/fluent/build/Debug/src/cereal_project/include
--   /vagrant_data/fluent/build/Debug/src/fmt_project
--   /vagrant_data/fluent/build/Debug/src/googlebenchmark_project/include
--   /vagrant_data/fluent/build/Debug/src/googlelog_project/src
--   /vagrant_data/fluent/build/Debug/src/googlelog_project-build
--   /vagrant_data/fluent/build/Debug/src/googletest_project/googletest/include
--   /vagrant_data/fluent/build/Debug/src/googletest_project/googlemock/include
--   /vagrant_data/fluent/build/Debug/src/grpc_project/third_party/protobuf/src
--   /vagrant_data/fluent/build/Debug/src/grpc_project/third_party/protobuf/src
--   /vagrant_data/fluent/build/Debug/src/grpc_project/include
--   /vagrant_data/fluent/build/Debug/src/libpqxx_project/include
--   /vagrant_data/fluent/build/Debug/src/range-v3_project/include
--   /vagrant_data/fluent/build/Debug/src/redox_project/include
--   /vagrant_data/fluent/build/Debug/src/zeromq_project/include
--   /vagrant_data/fluent/build/Debug/src/zeromqcpp_project
--   /vagrant_data/fluent/src/.
--   /vagrant_data/fluent/build/Debug
-- [link directories]
--   /vagrant_data/fluent/build/Debug/src/aws_project-build/aws-cpp-sdk-core
--   /vagrant_data/fluent/build/Debug/src/aws_project-build/aws-cpp-sdk-s3
--   /vagrant_data/fluent/build/Debug/src/cassandra_project-build
--   /vagrant_data/fluent/build/Debug/src/fmt_project-build/fmt
--   /vagrant_data/fluent/build/Debug/src/googlebenchmark_project-build/src
--   /vagrant_data/fluent/build/Debug/src/googlelog_project-build
--   /vagrant_data/fluent/build/Debug/src/googletest_project-build/googlemock/gtest
--   /vagrant_data/fluent/build/Debug/src/googletest_project-build/googlemock
--   /vagrant_data/fluent/build/Debug/src/grpc_project/third_party/protobuf/src/.libs
--   /vagrant_data/fluent/build/Debug/src/grpc_project/libs/opt
--   /vagrant_data/fluent/build/Debug/src/libpqxx_project/src/.libs
--   /vagrant_data/fluent/build/Debug/src/redox_project-build
--   /vagrant_data/fluent/build/Debug/src/zeromq_project/.libs
-- Configuring done
-- Generating done
-- Build files have been written to: /vagrant_data/fluent/build/Debug
[  2%] Built target zeromq_project
[  4%] Built target zeromqcpp_project
[  4%] Performing update step for 'redox_project'
[  6%] Built target range-v3_project
[  7%] Performing update step for 'googletest_project'
[  8%] Built target grpc_project
[  8%] Performing update step for 'cassandra_project'
[ 10%] Built target libpqxx_project
[ 10%] Performing configure step for 'googletest_project'
[ 12%] Built target cereal_project
[ 13%] Performing configure step for 'cassandra_project'
[ 14%] Performing update step for 'googlebenchmark_project'
-- Project version: 2.7.0
-- Using std::atomic implementation for atomic operations
-- Configuring done
[ 14%] Performing configure step for 'googlebenchmark_project'
-- Generating done
-- Build files have been written to: /vagrant_data/fluent/build/Debug/src/googletest_project-build
[ 15%] Performing build step for 'googletest_project'
-- git Version: v0.0.0
-- Version: 0.0.0
-- Performing Test HAVE_STD_REGEX
[ 36%] Built target gmock_main
Current branch master is up to date.
[ 15%] Performing configure step for 'redox_project'
[ 63%] Built target gmock
Building for x86_64
-- Configuring done
[ 81%] Built target gtest
-- Generating done
-- Build files have been written to: /vagrant_data/fluent/build/Debug/src/redox_project-build
[ 16%] Performing build step for 'redox_project'
[100%] Built target gtest_main
[ 16%] No install step for 'googletest_project'
[ 50%] Built target redox_static
[ 16%] Completed 'googletest_project'
[ 17%] Built target googletest_project
[100%] Built target redox
[ 17%] Performing update step for 'aws_project'
-- Using hash header <functional> and namespace "std"
-- Configuring done
[ 17%] No install step for 'redox_project'
[ 17%] Performing configure step for 'aws_project'
[ 18%] Completed 'redox_project'
-- TARGET_ARCH not specified; inferring host OS to be platform compilation target
-- Building AWS libraries as shared objects
-- Generating linux build config
[ 19%] Built target redox_project
-- Building project version: 1.1.7
[ 19%] Performing update step for 'fmt_project'
--   Zlib include directory: /usr/include
--   Zlib library: /usr/lib/x86_64-linux-gnu/libz.so
-- Encryption: Openssl
--   Openssl include directory: /usr/include
--   Openssl library: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so
-- Http client: Curl
--   Curl include directory: /usr/include/x86_64-linux-gnu
--   Curl library: /usr/lib/x86_64-linux-gnu/libcurl.so
-- Considering s3
[ 19%] Performing configure step for 'fmt_project'
-- CMake version: 3.5.1
-- Build type: Release
-- Target 'doc' disabled (requires doxygen)
-- Configuring done
-- Generating done
-- Generating done
-- Build files have been written to: /vagrant_data/fluent/build/Debug/src/cassandra_project-build
[ 19%] Performing build step for 'cassandra_project'
-- Build files have been written to: /vagrant_data/fluent/build/Debug/src/fmt_project-build
[ 19%] Performing build step for 'fmt_project'
[  2%] Linking CXX shared library libfmt.so
[ 10%] Built target fmt
[ 15%] Built target gmock
[ 20%] Built target noexception-test
-- Updating version info to 1.1.7
-- Performing Test HAVE_STD_REGEX -- success
-- Performing Test HAVE_GNU_POSIX_REGEX
-- Custom memory management enabled; stl objects now using custom allocators
[ 30%] Built target test-main
[ 45%] Built target posix-mock-test
-- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile
-- Performing Test HAVE_POSIX_REGEX
[ 47%] Linking CXX executable ../bin/posix-test
[ 50%] Built target posix-test
[ 52%] Linking CXX executable ../bin/ostream-test
-- Performing Test HAVE_POSIX_REGEX -- success
-- Performing Test HAVE_STEADY_CLOCK
-- Configuring done
[ 55%] Built target ostream-test
[ 57%] Linking CXX executable ../bin/printf-test
-- Performing Test HAVE_STEADY_CLOCK -- success
-- Configuring done
-- Generating done
-- Build files have been written to: /vagrant_data/fluent/build/Debug/src/googlebenchmark_project-build
[ 19%] Performing build step for 'googlebenchmark_project'
[ 60%] Built target printf-test
[ 62%] Linking CXX executable ../bin/util-test
[ 31%] Built target benchmark
[ 36%] Built target output_test_helper
[ 40%] Built target benchmark_test
-- Generating done
-- Build files have been written to: /vagrant_data/fluent/build/Debug/src/aws_project-build
[ 45%] Built target skip_with_error_test
[ 20%] Performing build step for 'aws_project'
[ 50%] Built target multiple_ranges_test
[ 54%] Built target register_benchmark_test
[ 65%] Built target util-test
[ 59%] Built target donotoptimize_test
[ 67%] Linking CXX executable ../bin/assert-test
[ 63%] Built target map_test
[ 68%] Built target fixture_test
[ 72%] Built target reporter_output_test
[ 77%] Built target complexity_test
[ 70%] Built target assert-test
[ 81%] Built target diagnostics_test
[ 72%] Linking CXX executable ../bin/macro-test
[  1%] Building CXX object CMakeFiles/cpp-driver.dir/src/token_aware_policy.cpp.o
[ 86%] Built target cxx03_test
[ 90%] Built target filter_test
[ 95%] Built target basic_test
[100%] Built target options_test
[ 75%] Built target macro-test
[ 85%] Built target header-only-test
[ 21%] No install step for 'googlebenchmark_project'
[ 21%] Completed 'googlebenchmark_project'
[ 87%] Linking CXX executable ../bin/format-impl-test
[ 21%] Built target googlebenchmark_project
[ 22%] Performing update step for 'googlelog_project'
[ 22%] Performing configure step for 'googlelog_project'
[ 90%] Built target format-impl-test
[ 92%] Linking CXX executable ../bin/format-test
CMake Warning at CMakeLists.txt:52 (find_package):
  By not providing "Findgflags.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "gflags", but
  CMake did not find one.

  Could not find a package configuration file provided by "gflags" with any
  of the following names:

    gflagsConfig.cmake
    gflags-config.cmake

  Add the installation prefix of "gflags" to CMAKE_PREFIX_PATH or set
  "gflags_DIR" to a directory containing one of the above files.  If "gflags"
  provides a separate development package or SDK, be sure it has been
  installed.

[ 95%] Built target format-test
[ 97%] Linking CXX executable ../bin/gtest-extra-test
[100%] Built target gtest-extra-test
[ 21%] Built target aws-cpp-sdk-core
[ 22%] No install step for 'fmt_project'
[ 22%] Completed 'fmt_project'
[ 24%] Built target fmt_project
[ 25%] Built target examples_distributed_kvs_proto
Scanning dependencies of target examples_file_system
[ 25%] Building CXX object examples/file_system/CMakeFiles/examples_file_system.dir/string_store.cc.o
[  2%] Building CXX object CMakeFiles/cpp-driver.dir/src/latency_aware_policy.cpp.o
[  3%] Building CXX object CMakeFiles/cpp-driver.dir/src/murmur3.cpp.o
[  5%] Building CXX object CMakeFiles/cpp-driver.dir/src/whitelist_policy.cpp.o
[ 26%] Linking CXX static library libexamples_file_system.a
[ 26%] Built target examples_file_system
[ 26%] Generating api.grpc.pb.cc, api.grpc.pb.h
[ 26%] Generating api.pb.cc, api.pb.h
Scanning dependencies of target examples_grcp_proto
[  6%] Building CXX object CMakeFiles/cpp-driver.dir/src/user_type_value.cpp.o
-- Configuring done
[ 26%] Building CXX object examples/grpc/CMakeFiles/examples_grcp_proto.dir/api.pb.cc.o
-- Generating done
-- Build files have been written to: /vagrant_data/fluent/build/Debug/src/googlelog_project-build
[ 27%] Performing build step for 'googlelog_project'
[  4%] Linking CXX shared library libglog.so
[ 36%] Built target glog
[ 40%] Linking CXX executable signalhandler_unittest
[  7%] Building CXX object CMakeFiles/cpp-driver.dir/src/address.cpp.o
[ 45%] Built target signalhandler_unittest
[ 50%] Linking CXX executable stl_logging_unittest
[ 54%] Built target stl_logging_unittest
[ 59%] Linking CXX executable stacktrace_unittest
[ 63%] Built target stacktrace_unittest
[ 68%] Linking CXX executable demangle_unittest
[  9%] Building CXX object CMakeFiles/cpp-driver.dir/src/cluster.cpp.o
[ 72%] Built target demangle_unittest
[ 77%] Linking CXX executable logging_unittest
[ 81%] Built target logging_unittest
[ 86%] Linking CXX executable symbolize_unittest
[ 90%] Built target symbolize_unittest
[ 95%] Linking CXX executable utilities_unittest
[100%] Built target utilities_unittest
[ 27%] No install step for 'googlelog_project'
[ 28%] Completed 'googlelog_project'
[ 28%] Built target googlelog_project
Scanning dependencies of target testing
[ 29%] Building CXX object testing/CMakeFiles/testing.dir/mock_clock.cc.o
[ 22%] Building CXX object aws-cpp-sdk-s3/CMakeFiles/aws-cpp-sdk-s3.dir/source/S3Client.cpp.o
[ 29%] Linking CXX static library libtesting.a
[ 29%] Built target testing
[ 30%] Building CXX object examples/grpc/CMakeFiles/examples_grcp_proto.dir/api.grpc.pb.cc.o
[ 10%] Building CXX object CMakeFiles/cpp-driver.dir/src/round_robin_policy.cpp.o
[ 11%] Building CXX object CMakeFiles/cpp-driver.dir/src/timestamp_generator.cpp.o
[ 13%] Building CXX object CMakeFiles/cpp-driver.dir/src/get_time-unix.cpp.o
[ 14%] Building CXX object CMakeFiles/cpp-driver.dir/src/collection.cpp.o
[ 15%] Building CXX object CMakeFiles/cpp-driver.dir/src/tuple.cpp.o
Scanning dependencies of target ra_logical_to_debug_string_test
[ 17%] Building CXX object CMakeFiles/cpp-driver.dir/src/third_party/hdr_histogram/hdr_histogram.cpp.o
[ 31%] Building CXX object ra/logical/CMakeFiles/ra_logical_to_debug_string_test.dir/to_debug_string_test.cc.o
[ 18%] Building CXX object CMakeFiles/cpp-driver.dir/src/third_party/curl/hostcheck.cpp.o
[ 19%] Building CXX object CMakeFiles/cpp-driver.dir/src/ssl/ssl_openssl_impl.cpp.o
[ 21%] Building CXX object CMakeFiles/cpp-driver.dir/src/ssl/ring_buffer_bio.cpp.o
[ 97%] Built target cpp-driver
Scanning dependencies of target cassandra
[ 98%] Linking CXX shared library libcassandra.so
virtual memory exhausted: Cannot allocate memory
ra/logical/CMakeFiles/ra_logical_to_debug_string_test.dir/build.make:62: recipe for target 'ra/logical/CMakeFiles/ra_logical_to_debug_string_test.dir/to_debug_string_test.cc.o' failed
make[2]: *** [ra/logical/CMakeFiles/ra_logical_to_debug_string_test.dir/to_debug_string_test.cc.o] Error 1
CMakeFiles/Makefile2:4433: recipe for target 'ra/logical/CMakeFiles/ra_logical_to_debug_string_test.dir/all' failed
make[1]: *** [ra/logical/CMakeFiles/ra_logical_to_debug_string_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Scanning dependencies of target cassandra_static
[ 98%] Built target cassandra
[ 22%] Building CXX object aws-cpp-sdk-s3/CMakeFiles/aws-cpp-sdk-s3.dir/source/model/FilterRuleName.cpp.o
[100%] Linking CXX static library libcassandra_static.a
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-6/README.Bugs> for instructions.
aws-cpp-sdk-s3/CMakeFiles/aws-cpp-sdk-s3.dir/build.make:138: recipe for target 'aws-cpp-sdk-s3/CMakeFiles/aws-cpp-sdk-s3.dir/source/S3Client.cpp.o' failed
make[5]: *** [aws-cpp-sdk-s3/CMakeFiles/aws-cpp-sdk-s3.dir/source/S3Client.cpp.o] Error 4
make[5]: *** Waiting for unfinished jobs....
Scanning dependencies of target testing-resources
CMakeFiles/Makefile2:117: recipe for target 'aws-cpp-sdk-s3/CMakeFiles/aws-cpp-sdk-s3.dir/all' failed
make[4]: *** [aws-cpp-sdk-s3/CMakeFiles/aws-cpp-sdk-s3.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
[ 22%] Building CXX object testing-resources/CMakeFiles/testing-resources.dir/source/MemoryTesting.cpp.o
[ 23%] Building CXX object testing-resources/CMakeFiles/testing-resources.dir/source/TestingEnvironment.cpp.o
[ 31%] Linking CXX static library libexamples_grcp_proto.a
[ 23%] Building CXX object testing-resources/CMakeFiles/testing-resources.dir/source/external/gtest-all.cc.o
[ 31%] Built target examples_grcp_proto
[ 23%] Building CXX object testing-resources/CMakeFiles/testing-resources.dir/source/platform/linux-shared/PlatformTesting.cpp.o
[100%] Built target cassandra_static
[ 31%] No install step for 'cassandra_project'
[ 31%] Completed 'cassandra_project'
[ 32%] Built target cassandra_project
[ 24%] Linking CXX shared library libtesting-resources.so
[ 24%] Built target testing-resources
Makefile:127: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/aws_project.dir/build.make:110: recipe for target 'src/aws_project-stamp/aws_project-build' failed
make[2]: *** [src/aws_project-stamp/aws_project-build] Error 2
CMakeFiles/Makefile2:437: recipe for target 'CMakeFiles/aws_project.dir/all' failed
make[1]: *** [CMakeFiles/aws_project.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by mwhittaker** [comment]
> virtual memory exhausted: Cannot allocate memory

Looks like you ran out of memory? Running `./scripts/build.sh Debug 1` which uses one thread rather than `./scripts/build.sh Debug 4` which uses 4 might help avoid exhausting memory.

**Comment by gaberger** [comment]
Thanks @mwhittaker already exhausted 4G trying to compile fluent_kvs_server. Any idea how much memory you guys are using?

virtual memory exhausted: Cannot allocate memory
examples/fluent_kvs/CMakeFiles/examples_fluent_kvs_server.dir/build.make:62: recipe for target 'examples/fluent_kvs/CMakeFiles/examples_fluent_kvs_server.dir/server.cc.o' failed
make[2]: *** [examples/fluent_kvs/CMakeFiles/examples_fluent_kvs_server.dir/server.cc.o] Error 1
CMakeFiles/Makefile2:2619: recipe for target 'examples/fluent_kvs/CMakeFiles/examples_fluent_kvs_server.dir/all' failed
make[1]: *** [examples/fluent_kvs/CMakeFiles/examples_fluent_kvs_server.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by mwhittaker** [comment]
@gaberger, sorry for all the build woes! I don't know exactly how much we use, but we use a lot :P. Unfortunately, the code uses a ton of template metaprogramming which seems to make compilers use a ton of memory. 

I know that master builds on [travis](https://travis-ci.org/ucbrise/fluent/branches) using clang++, and I think travis machines only have 3 GB of memory. I also know that g++ uses a lot more memory than clang++ when compiling fluent. @gaberger, are you using g++? If so, I suggest trying to use clang++ instead.
