### ISSUE TITLE
Examples launch script error out on Ubuntu 16.04 due to tmux arguments

### ISSUE THREAD

**Issue by gaberger** [ucbrise/fluent#114]
Due to the set -e, the `tmux new-window` command fails trying to allocate a window that is already indexed to 0.
```
$ ./src/examples/kvs/launch_kvs.sh
+ main
+ [[ -z dummy ]]
++ tmux display-message -p '#S'
+ session=0
+ tmux new-window -t 0 -n kvs
create window failed: index in use: 0
```

Adding `-t` to the display-message command solves this

`session="$(tmux display-message -t -p '#S')"`

**Comment by mwhittaker** [comment]
Thanks so much for the bug report @gaberger! Those scripts are definitely buggy. I'm not exactly sure what I was thinking when I wrote that code 😝 . PR #115 fixes this issue.
